version: '3'

services:
  web:
    build: .
    command: bash -c "gunicorn wsgi:application --bind 127.0.0.1:8090"
    container_name: football_dashboard
    expose:
      - 8090
    env_file:
      - ./.env.dev
    depends_on:
      - db

  db:
    build:
      context: ./data
      dockerfile: Dockerfile
    volumes: 
      - pgdata:/var/lib/postgresql/data
    expose:
      - 5432    
    environment:
      - POSTGRES_DB=football_dashboard
      - POSTGRES_USER=valentinmonsimier
      - POSTGRES_PASSWORD=Sacamerde8932!
    container_name: football_database

volumes:
  pgdata:
  