version: '3'

services:
  web:
    build: .
    command: gunicorn --chdir web/staticfiles wsgi:application --bind 10.0.0.8:80
    container_name: football_dashboard
    volumes:
      - static_volume:/usr/src/app/web/staticfiles
    networks:
      netfoot:
        ipv4_address: 10.0.0.8
    expose:
      - 80
    env_file:
      - ./.env.dev
    depends_on:
      - db

  db:
    build:
      context: ./data
      dockerfile: Dockerfile
    volumes: 
      - pgdata:/var/lib/postgresql/data
    networks:
      netfoot:
        ipv4_address: 10.0.0.5
    environment:
      - POSTGRES_DB=football_dashboard
      - POSTGRES_USER=valentinm
      - POSTGRES_PASSWORD=Sacamerde8932!
    container_name: football_database

networks:
  netfoot:
    driver: bridge
    ipam:
     config:
        - subnet: 10.0.0.0/16

volumes:
  pgdata:
  static_volume:
  