version: '3'

services:
  nginx:
    build: 
      context: ./nginx
      dockerfile: Dockerfile
    volumes:
      - static_volume:/usr/src/app
    container_name: nginx_server
    ports:
      - 8000:8000
    expose:
      - 1337
    depends_on:
      - web

  web:
    build: .
    command: gunicorn --chdir web/staticfiles wsgi:application --bind 0.0.0.0:8000
    container_name: football_dashboard
    volumes:
      - static_volume:/usr/src/app
    expose:
      - 8000
    env_file:
      - ./.env.dev
    depends_on:
      - db

  db:
    build:
      context: ./data
      dockerfile: Dockerfile
    volumes: 
      - pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=football_dashboard
      - POSTGRES_USER=valentinm
      - POSTGRES_PASSWORD=Sacamerde8932!
    container_name: football_database

volumes:
  pgdata:
  static_volume:
  