# Generated by Django 4.0 on 2021-12-18 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Scrappers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('path', models.FilePathField()),
                ('in_execution', models.BooleanField(default=False)),
                ('enable', models.BooleanField(default=False)),
                ('current_pid', models.PositiveIntegerField(default=None)),
                ('errors', models.TextField()),
            ],
        ),
    ]
