# Generated by Django 4.0 on 2021-12-21 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('run_script', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scrappers',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='scrappers',
            name='path',
            field=models.CharField(max_length=64),
        ),
    ]
