# Generated by Django 4.0 on 2021-12-21 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('run_script', '0002_alter_scrappers_name_alter_scrappers_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scrappers',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
