# Generated by Django 4.0 on 2021-12-28 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('run_script', '0003_alter_scrappers_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrappers',
            name='last_execution',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
