# Generated by Django 4.0 on 2021-12-29 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('run_script', '0004_scrappers_last_execution'),
    ]

    operations = [
        migrations.CreateModel(
            name='FbrefLinks',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('link', models.CharField(max_length=120)),
                ('league', models.CharField(max_length=50)),
                ('season', models.PositiveIntegerField()),
            ],
        ),
    ]
