# Generated by Django 4.0 on 2021-12-29 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('run_script', '0005_fbreflinks'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrappers',
            name='site',
            field=models.CharField(default='', max_length=40),
        ),
    ]
