# Generated by Django 4.0 on 2021-12-29 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('run_script', '0006_scrappers_site'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scrapper_Active_Links',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('scrapper_id', models.PositiveIntegerField()),
                ('link', models.CharField(max_length=120)),
            ],
        ),
    ]
