# Generated by Django 4.0 on 2021-12-30 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('run_script', '0007_scrapper_active_links'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exclude_Player_Links',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('scrapper_id', models.PositiveIntegerField()),
                ('link', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Exclude_Team_Links',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('scrapper_id', models.PositiveIntegerField()),
                ('link', models.CharField(max_length=120)),
            ],
        ),
    ]
