# Generated by Django 4.0 on 2022-01-10 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('run_script', '0011_alter_scrapper_active_links_season'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScrapperLogs',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('scrapper_id', models.PositiveIntegerField()),
                ('type', models.CharField(max_length=5)),
                ('text', models.CharField(max_length=200)),
                ('date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
