# Generated by Django 4.0 on 2022-01-29 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('run_script', '0012_scrapperlogs'),
    ]

    operations = [
        migrations.CreateModel(
            name='Files',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('path', models.CharField(max_length=120)),
                ('player', models.CharField(default=None, max_length=100)),
                ('team', models.CharField(max_length=45)),
                ('league', models.CharField(max_length=50)),
                ('season', models.PositiveIntegerField()),
                ('dateIns', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
