# Generated by Django 4.0 on 2022-03-03 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('run_script', '0013_files'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scrappers',
            name='errors',
            field=models.TextField(default=None),
        ),
    ]
