# Generated by Django 4.0.5 on 2022-10-29 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('run_script', '0016_delete_files_delete_scrapperlogs'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tests',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('path', models.CharField(max_length=64)),
                ('last_excution', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
