# Generated by Django 4.0.5 on 2022-10-29 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('run_script', '0019_tests_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestFiles',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('path', models.CharField(max_length=100)),
                ('is_result', models.BooleanField(default=False)),
            ],
        ),
    ]
